-- Migration 0002 — drop `auth`.
-- Sprint 5 (US-M8.1/M8.2) traced the actual login sequence and found `auth`
-- unreadable in principle: it lives inside the SQLCipher-encrypted file, but
-- opening that file requires unwrapping a credential envelope that would
-- have been stored in a row of this very table — circular. Credential
-- envelopes and lockout state now live in an unencrypted sidecar file next
-- to the database (safe to leave unencrypted: it holds only AES-GCM-wrapped
-- copies of the master key, never the master key or a credential itself —
-- see src-tauri/src/m8_auth/store.rs). No client data has ever existed in
-- this table; nothing is lost by dropping it.
DROP TABLE auth;
